#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# World
/gate/world/geometry/setXLength 50 cm
/gate/world/geometry/setYLength 50 cm
/gate/world/geometry/setZLength 50 cm
/gate/world/setMaterial Air


# Boxes
/gate/world/daughters/name              box0
/gate/world/daughters/insert            box
/gate/box0/geometry/setXLength      20 cm
/gate/box0/geometry/setYLength      2 cm
/gate/box0/geometry/setZLength      20 cm
/gate/box0/placement/setTranslation 0.0 10.0 0.0 cm
/gate/box0/setMaterial Air
/gate/box0/vis/setVisible 1
/gate/box0/vis/setColor cyan

/gate/world/daughters/name              box1
/gate/world/daughters/insert            box
/gate/box1/geometry/setXLength      20 cm
/gate/box1/geometry/setYLength      2 cm
/gate/box1/geometry/setZLength      20 cm
/gate/box1/placement/setTranslation 0.0 8.0 0.0 cm
/gate/box1/setMaterial Air
/gate/box1/vis/setVisible 1
/gate/box1/vis/setColor red

/gate/world/daughters/name              box2
/gate/world/daughters/insert            box
/gate/box2/geometry/setXLength      20 cm
/gate/box2/geometry/setYLength      2 cm
/gate/box2/geometry/setZLength      20 cm
/gate/box2/placement/setTranslation 0.0 6.0 0.0 cm
/gate/box2/setMaterial Air
/gate/box2/vis/setVisible 1
/gate/box2/vis/setColor blue

#system
/gate/world/daughters/name              scanner
/gate/world/daughters/insert            box
/gate/scanner/geometry/setXLength      20 cm
/gate/scanner/geometry/setYLength      1 mm
/gate/scanner/geometry/setZLength      20 cm
/gate/scanner/placement/setTranslation 0.0 0.0 0.0 cm
/gate/scanner/setMaterial Air
/gate/scanner/vis/setVisible 1
/gate/scanner/vis/setColor cyan

#sensor
#/gate/scanner/daughters/name sensor1
#/gate/scanner/daughters/insert box
#/gate/sensor1/geometry/setXLength      20 cm
#/gate/sensor1/geometry/setYLength      0.174 mm
#/gate/sensor1/geometry/setZLength      20 cm
#/gate/sensor1/setMaterial Silicon
#/gate/sensor1/placement/setTranslation 0.0 0.0 0.0 cm
#/gate/sensor1/vis/setVisible 1
#/gate/sensor1/vis/setColor yellow
#/gate/systems/scanner/level1/attach sensor1
#/gate/sensor1/attachCrystalSD
/control/execute mac/sensor1.mac



# /gate/geometry/setIonisationPotential Water 75 eV
# /gate/geometry/setIonisationPotential Air 85.7 eV



#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList QGSP_BERT_EMV

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      box0 0.1 mm
/gate/physics/Electron/SetCutInRegion   box0 0.1 mm
/gate/physics/Positron/SetCutInRegion   box0 0.1 mm

/gate/physics/Gamma/SetCutInRegion      box1 0.1 mm
/gate/physics/Electron/SetCutInRegion   box1 0.1 mm
/gate/physics/Positron/SetCutInRegion   box1 0.1 mm

/gate/physics/Gamma/SetCutInRegion      box2 0.1 mm
/gate/physics/Electron/SetCutInRegion   box2 0.1 mm
/gate/physics/Positron/SetCutInRegion   box2 0.1 mm

/gate/physics/Gamma/SetCutInRegion      scanner 0.1 mm
/gate/physics/Electron/SetCutInRegion   scanner 0.1 mm
/gate/physics/Positron/SetCutInRegion   scanner 0.1 mm

/gate/physics/SetMaxStepSizeInRegion world 1 mm
/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter deuteron
/gate/physics/ActivateStepLimiter triton
/gate/physics/ActivateStepLimiter alpha
/gate/physics/ActivateStepLimiter GenericIon

/gate/physics/displayCuts

#/gate/physics/addProcess LowEnergyHadronIonisation
/gate/physics/addProcess HadronIonisation proton

#================================================================
#     ACTORS
#================================================================


/gate/actor/addActor ProtonNuclearInformationActor myNuclearInfoActor
/gate/actor/myNuclearInfoActor/attachTo            world

/gate/actor/addActor PhaseSpaceActor         tracker0
/gate/actor/tracker0/save                     tracker0.root
/gate/actor/tracker0/attachTo                 box0
/gate/actor/tracker0/enableProductionProcess  false
#/gate/actor/tracker0/useVolumeFrame           true
/gate/actor/tracker0/storeOutgoingParticles true
/gate/actor/tracker0/enableNuclearFlag          true

/gate/actor/addActor PhaseSpaceActor         tracker1
/gate/actor/tracker1/save                     tracker1.root
/gate/actor/tracker1/attachTo                 box1
/gate/actor/tracker1/enableNuclearFlag          true
/gate/actor/tracker1/enableProductionProcess  false
#/gate/actor/tracker1/useVolumeFrame           true
/gate/actor/tracker1/storeOutgoingParticles true


/gate/actor/addActor PhaseSpaceActor         tracker2
/gate/actor/tracker2/save                     tracker2.root
/gate/actor/tracker2/attachTo                 box2
/gate/actor/tracker2/enableNuclearFlag          true
/gate/actor/tracker2/enableProductionProcess  false
#/gate/actor/tracker2/useVolumeFrame           true
/gate/actor/tracker2/storeOutgoingParticles true

/gate/actor/addActor PhaseSpaceActor         tracker3
/gate/actor/tracker3/save                     tracker3.root
/gate/actor/tracker3/attachTo                 sensor1
/gate/actor/tracker3/enableNuclearFlag          true
/gate/actor/tracker3/enableProductionProcess  false
#/gate/actor/tracker3/useVolumeFrame           true
/gate/actor/tracker3/storeOutgoingParticles true
#==================================================
# OUTPUT
#==================================================
/gate/output/root/enable
/gate/output/root/setFileName TrackerHits
/gate/output/root/setRootHitFlag            1
/gate/output/root/setRootSinglesFlag        0
#/gate/output/root/setRootCoincidencesFlag   0
/gate/output/root/setRootNtupleFlag         0
/gate/output/root/setRootOpticalFlag        0

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# Enable the following lines to display available and enabled processes
# /gate/physics/processList Available
# /gate/physics/processList Enabled

#=====================================================
# BEAMS
#=====================================================
/gate/source/addSource PBS PencilBeam
/gate/source/PBS/setParticleType proton
/gate/source/PBS/setEnergy 7116 MeV
/gate/source/PBS/setSigmaEnergy 1.0 MeV
/gate/source/PBS/setPosition 0 250 0 mm
/gate/source/PBS/setSigmaX 2 mm
/gate/source/PBS/setSigmaY 2 mm
/gate/source/PBS/setSigmaTheta 3 mrad
/gate/source/PBS/setSigmaPhi 3 mrad
/gate/source/PBS/setEllipseXThetaEmittance 15 mm*mrad
#/gate/source/PBS/setEllipseXThetaRotationNorm negative
/gate/source/PBS/setEllipseYPhiEmittance 15 mm*mrad
/gate/source/PBS/setEllipseYPhiRotationNorm negative
/gate/source/PBS/setRotationAxis 1 0 0
/gate/source/PBS/setRotationAngle 90 deg
/gate/application/setTotalNumberOfPrimaries 10000

#=====================================================
# VISUALISATION
#=====================================================

/control/execute mac/visu.mac

#=====================================================
# START BEAMS
#=====================================================

# JamesRandom Ranlux64 MersenneTwister
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed 123456

# /gate/random/verbose 1
# /gate/source/verbose 0

# to check Steplimiter
#/tracking/verbose 1

#/gate/application/noGlobalOutput
#/gate/application/setTotalNumberOfPrimaries 200
#===============================================
# OUTPUT SETTINGS
#===============================================




/gate/application/start

exit
