#sensor
/gate/scanner/daughters/name sensor1
/gate/scanner/daughters/insert box
/gate/sensor1/geometry/setXLength      20 cm
/gate/sensor1/geometry/setYLength      0.1 mm
/gate/sensor1/geometry/setZLength      20 cm
/gate/sensor1/setMaterial Silicon
/gate/sensor1/placement/setTranslation 0.0 0.0 0.0 cm
/gate/sensor1/vis/setVisible 1
/gate/sensor1/vis/setColor yellow
/gate/systems/scanner/level1/attach sensor1
/gate/sensor1/attachCrystalSD
