# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MacroWriter": "00_macrotools.ipynb",
         "create_all": "00_macrotools.ipynb",
         "run_macro": "00_macrotools.ipynb",
         "Ek": "00_macrotools.ipynb",
         "find_max_nonzero": "01_analysis.ipynb",
         "find_range": "01_analysis.ipynb",
         "get_edep_data": "01_analysis.ipynb",
         "get_df_subentry2": "01_analysis.ipynb"}

modules = ["macrotools.py",
           "analysis.py"]

doc_url = "https://dmitryhits.github.io/ProtonBeamTherapy/"

git_url = "https://github.com/dmitryhits/ProtonBeamTherapy/tree/master/"

def custom_doc_links(name): return None
