# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Ek": "00_core.ipynb",
         "create_sensor": "00_core.ipynb",
         "create_phantom_layer": "00_core.ipynb",
         "create_beam": "00_core.ipynb",
         "create_start_beams": "00_core.ipynb",
         "create_macro_file": "00_core.ipynb",
         "run_macro": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://dmitryhits.github.io/gate_simulation/"

git_url = "https://github.com/dmitryhits/gate_simulation/tree/master/"

def custom_doc_links(name): return None
