# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://dmitryhits.github.io/gate_simulation/"

git_url = "https://github.com/dmitryhits/gate_simulation/tree/master/"

def custom_doc_links(name): return None
