# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['create_sensor']

# Cell
def create_sensor(n=0, x_length=20, z_length=20, thickness=0.1, x_loc=0, y_loc=0, z_loc=0,
                  system='scanner', material='Silicon'):
    '''
    This function will create a GATE macro for creating a sensor
    which in the current implementation is a flat plane perpendicular to beam which is in y direction
    thickness dimension is in mm
    all other dimensions are in cm
    '''


    lines = f"""#sensor
    /gate/scanner/daughters/name sensor{n}
    /gate/{system}/daughters/insert box
    /gate/sensor{n}/geometry/setXLength      {x_length} cm
    /gate/sensor{n}/geometry/setYLength      {thickness} mm
    /gate/sensor{n}/geometry/setZLength      {z_length} cm
    /gate/sensor{n}/setMaterial {material}
    /gate/sensor{n}/placement/setTranslation {x_loc} {y_loc} {z_loc} cm
    /gate/sensor{n}/vis/setVisible 1
    /gate/sensor{n}/vis/setColor yellow
    /gate/systems/{system}/level1/attach sensor{n}
    /gate/sensor{n}/attachCrystalSD"""
    # lines = lines.split('\n')
    # print(lines)
    # for i, line in enumerate(lines):
    #     print(i, line)

    with open(f'mac/sensor{n}.mac', 'w') as file:
        file.write(lines)
        # file.write('\n'.join(lines)+'\n')